name: CHESS CI
env:
  NODE_VERSION : "6.x"
  AWS_REGION   : "eu-central-1"
on:
  pull_request:
    branches: 
      - master
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Setup node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Gazer dependencies
      run: npm install
      
    - name: Test app
      run: npm test 

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Status message to Telegram
      uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.TG_USER }}
        token: ${{ secrets.TG_TOKEN }}
        status: ${{ job.status }}
